[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["E","F","W","I","N","UP","B","SIM"]
ignore = ["E501"]

[tool.pytest.ini_options]
testpaths = ["tests"]
